INSERT INTO `genre` (nombre, `Description`) VALUES ('Adventure', 'ecsiting and interesting games');
INSERT INTO `genre` (nombre, `Description`) VALUES ('Horror', 'Games that most people get scared from');
INSERT INTO `genre` (nombre, `Description`) VALUES ('Strategy', 'Games with strategies, city planing for example');
INSERT INTO `genre` (nombre, `Description`) VALUES ('Simulation Racing', 'Racing games that are very realistic');
INSERT INTO `genre` (nombre, `Description`) VALUES ('Arcade Racing', 'Racing games that are more casual/arcade like less realistic');
INSERT INTO `genre` (nombre, `Description`) VALUES ('Shooter', 'Games in where people shoot with a weapon or have wars');
INSERT INTO `genre` (nombre, `Description`) VALUES ('Multiplayer', 'Games where people play together');
INSERT INTO `Sellingwebsite` (`nombre`, `link`) VALUES ('MMOGA', 'https://www.mmoga.es/?gclid=CjwKCAiA85efBhBbEiwAD7oLQJbJmTO1ZtVTDFDRNmJPZwL6aAa2AZDuifAm0WMheHsao1hzi1nVMxoC4-kQAvD_BwE');
INSERT INTO `Sellingwebsite` (`nombre`, `link`) VALUES('Instant Gaming', 'https://www.instant-gaming.com/de/?igr=gamer-cb871fb&gclid=CjwKCAiA85efBhBbEiwAD7oLQDmWP9mDnmk4X8cdQw0CTlX1UYXQfmtBAZv0Q3lXgi5xfYyvjwwPNxoCzOQQAvD_BwE');
INSERT INTO `Sellingwebsite` (`nombre`, `link`) VALUES('Steam', 'https://store.steampowered.com/');
INSERT INTO `Sellingwebsite` (`nombre`, `link`) VALUES('G2A', 'https://www.g2a.com/de/?adid=GA-ES_PB_NGAM_SN_BRAND-English&id=35&gclid=CjwKCAiA85efBhBbEiwAD7oLQE0ehb-EVXMfJavKVN1CGSUtnyucYmSukglCOqvHs0Pxe8v7poSPQhoCWVAQAvD_BwE&gclsrc=aw.ds');
INSERT INTO `Sellingwebsite` (`nombre`, `link`) VALUES('Kinguin', 'https://www.kinguin.net/?gclid=CjwKCAiA85efBhBbEiwAD7oLQEdNUTq00jerrzG4EfwuAAPEF4Ef-Vys06BjHp_EcLaItrVKnyslcxoCrCMQAvD_BwE');
